### PR TITLE
Introduce sargraph2 - a sadf plotter

### PR DESCRIPTION
**Pull request by jimis**
Reimplemented most of the functionality of "sargraph" without any XML
transformations. Tweaked the graphs to be more meaningful and more beautiful,
and enabled optional output to file.

### CODE REVIEW

**Comment by jimis** [comment]
Example plots:

[cpu](http://i.imgur.com/4zSaaqN.png)

[mem](http://i.imgur.com/AYJr06g.png)

[io](http://i.imgur.com/Mp3rMTv.png)

**Comment by sysstat** [comment]
Impressive!
I noticed a small bug anyway (I'm letting you fix it). On my machine:

```
$ ./sargraph2
Headers not in right order:
$ sar
Linux 3.18.7-100.fc20.x86_64 (kluane.home) 	03/03/2015 	_x86_64_	(8 CPU)

05:34:07 PM       LINUX RESTART	(8 CPU)

05:35:00 PM     CPU     %user     %nice   %system   %iowait    %steal     %idle
05:40:00 PM     all      0.91     24.36      0.41      1.02      0.00     73.30
05:45:00 PM     all      1.04     49.58      0.48      0.40      0.00     48.50
...
$ sadf -t -d -C -- -u
kluane.home;-1;2015-03-03 17:34:07;LINUX-RESTART	(8 CPU)
# hostname;interval;timestamp;CPU;%user;%nice;%system;%iowait;%steal;%idle
kluane.home;300;2015-03-03 17:40:00;-1;0.91;24.36;0.41;1.02;0.00;73.30
kluane.home;300;2015-03-03 17:45:00;-1;1.04;49.58;0.48;0.40;0.00;48.50
...
```
As you can notice, the header line displayed by sadf is not the first one. You should first remove the possible LINUX RESTART messages located before.
In cpu_gnuplot, use something like
```
HEADER=`grep -v RESTART $2 | head -1 | cut -d ';' -f 5-10`
```

**Comment by sysstat** [comment]
I have just made an additional test. There may also be comments before the header line that should be removed:
```
# sadf -t -d -C -- -u
kluane.home;-1;2015-04-03 11:30:38;LINUX-RESTART	(8 CPU)
kluane.home;-1;2015-04-03 11:30:48;COM This is a comment
# hostname;interval;timestamp;CPU;%user;%nice;%system;%iowait;%steal;%idle
kluane.home;1;2015-04-03 11:31:18;-1;0.25;37.50;0.38;0.00;0.00;61.88
...
```
So the proper syntax in cpu_gnuplot() should be something like:
```
HEADER=`egrep -v "RESTART|COM" $2 | head -1 | cut -d ';' -f 5-10`
```

**Comment by jimis** [comment]
Thanks, fixed with pull request #62. 

But shouldn't it also be fixed in `sadf`? A header line should come even before comments, it's a header after all.

**Comment by jimis** [comment]
Another assumption I made in `sargraph2` is that the order of existing fields in the output of `sadf` will never change. I mean it's expected to append more fields, but the existing ones will not be moved. Is that a safe assumption?

**Comment by sysstat** [comment]
__Header line position:__
No, the header line is just ahead of its corresponding statistics. See below for two activities (-u and -w) displayed by sadf:
```
$ sadf -t -d -C data -- -uw
kluane.home;-1;2015-04-04 14:51:28;LINUX-RESTART	(8 CPU)
# hostname;interval;timestamp;CPU;%user;%nice;%system;%iowait;%steal;%idle
kluane.home;1;2015-04-04 14:51:35;-1;0.13;50.06;0.13;0.00;0.00;49.69
kluane.home;16;2015-04-04 14:51:51;-1;0.14;49.99;0.10;0.06;0.00;49.70
kluane.home;1;2015-04-04 14:51:52;-1;0.13;50.06;0.13;0.13;0.00;49.56
# hostname;interval;timestamp;proc/s;cswch/s
kluane.home;1;2015-04-04 14:51:35;0.00;632.00
kluane.home;16;2015-04-04 14:51:51;0.50;596.44
kluane.home;1;2015-04-04 14:51:52;0.00;702.00
```
There may even be several header lines for the same activity (for example if a system restart has happened):
```
$ sadf -t -d -C data -- -u
kluane.home;-1;2015-04-04 14:51:28;LINUX-RESTART	(8 CPU)
# hostname;interval;timestamp;CPU;%user;%nice;%system;%iowait;%steal;%idle
kluane.home;1;2015-04-04 14:51:35;-1;0.13;50.06;0.13;0.00;0.00;49.69
kluane.home;16;2015-04-04 14:51:51;-1;0.14;49.99;0.10;0.06;0.00;49.70
kluane.home;1;2015-04-04 14:51:52;-1;0.13;50.06;0.13;0.13;0.00;49.56
kluane.home;-1;2015-04-04 14:52:25;LINUX-RESTART	(8 CPU)
# hostname;interval;timestamp;CPU;%user;%nice;%system;%iowait;%steal;%idle
kluane.home;1;2015-04-04 14:53:35;-1;0.13;50.06;0.13;0.00;0.00;49.69
```
__Order of fields:__
Your assumption is reasonably safe. I will always try to not change the order (or the name) of fields in the output of sar (and sadf) although there have already been exceptions to the rule in the past (for example, fields rxkB/s and txkB/s were renamed in network interface statistics to be expressed in kB/s.They were previously expressed in bytes/s and had another name).

**Pull request merged**
