### PR TITLE
ignoring autofs as real filesystem by counting number of valid filesy…

### PR DESCRIPTION
**Pull request by odubaj**
…stems and getting all valid filesystems

Not mounted autofs filesystem is not a valid filesystem until it is mounted. For that reason it can not be counted as one of the valid filesystems and should not be display in system statistics.

### CODE REVIEW

**Comment by sysstat** [comment]
I agree that sar shouldn't make the system mount autofs filesystems just to be able to read its statistics. So OK, we don't have to count them as valid filesystems. But then if such a filesystem appears in the /etc/mtab file, doesn't it mean that it is already mounted? In this case reading its statistics shouldn't be a problem?

**Comment by odubaj** [comment]
In my opinion, automount works like this:

filesystem type autofs has a record in /etc/mtab even if the real filesystem is not mounted. When the user accesses the folder on which the autofs filesystem is pointing at, it mounts the real filesystem and adds new record about the mounted filesystem to /etc/mtab, but it does not detele the record of type autofs.

So that means that we cannot count records of type autofs as valid filesystems, due to they are not real filesystems and if they are mounted, a new record is added to /etc/mtab and this record should be counted. 

In our case, /etc/mtab is only a symlink to /proc/mounts, so these 2 files are identical

We can reproduce it on fedora 28 like this:
$ grep autofs /proc/mounts
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=51,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16792 0 0

$ cd /proc/sys/fs/binfmt_misc

$ grep binfmt_misc /proc/mounts
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=51,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16792 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0

**Comment by sysstat** [comment]
The (very) basic test I made couldn't reproduce the problem. Just reading /etc/mtab and statfs()'ing the various mount points (including those related to autofs) didn't trigger mounting autofs filesystems on my machine.
In your PR #210, you wrote:

Steps to Reproduce:
    rm -rf sa.new ; strace -fttT -o sadc.trc /usr/lib64/sa/sadc -F -L 1 2 sa.new ; grep mtab sadc.trc

Doing this, I can actually see that /etc/mtab has been opened and that there have been multiple statfs() calls, but I don't have any autofs filesystems mounted (though I can automount them manually e.g. if I try to read a file on them).

Can you give me a sample configuration (contents of /etc/auto.master and /etc/auto.XXX files, etc.) which will show the bug?

**Comment by odubaj** [comment]
I think PR #210 is something a little bit different.
This can be reproduced by creating autofs filesystem on your system, for example named /myfilesystem and mounted on mountpoint /dev/tmp. After creating such filesystem a new record will be saved in /etc/mtab and will look like

/myfilesystem /dev/tmp autofs rw, relatime ... other data

The problem is that such record in /etc/mtab will be counted as a valid filesystem, because the only condition for checking if filesystem is valid si "/" at the beginning of line (line represents one record in /etc/mtab). That is the reason, why there should be addded another condition checking if type of filesystem is autofs and if it is, skip it. As I already metioned, that if the autofs filesystem will be mounted a new valid record will be added to /etc/mtab. That is the reason, why should we ignore records of autofs type in /etc/mtab and the added condition implements it.

**Pull request merged**
