### PR TITLE
avoiding triggering automounts, bug #1670060

### PR DESCRIPTION
**Pull request by odubaj**

### CODE REVIEW

**Comment by sysstat** [comment]
Please could you add a description of the bug and how to reproduce it, or at least a link pointing at the bugzilla describing it?

**Comment by odubaj** [comment]
Hello,
aplologize, I forgot about that. Here is a link to described bug with steps to reproduce and also a fix from Martin Poole. It works, but in my opinion it should be fixed also for input:

rm -rf sa.new ; strace -fttT -o sadc.trc ./sadc -S XDISK 1 1 sa.new; grep mtab sadc.trc

The fix is probably in ignoring autofs, but I am still working on it.

Bug description here:

https://bugzilla.redhat.com/show_bug.cgi?id=1670060

Thanks!

**Comment by sysstat** [comment]
Sorry but I don't have access to that Bugzilla repository ("access denied").

**Comment by sysstat** [comment]
This patch seems to be no longer necessary if patch from PR #211 is applied.
Indeed if filesystem's type is autofs then the corresponding count function (`get_filesystem_nr()` in count.c) skips it and doesn't call statvfs() on the mount point, thus keeping the filesystem from being mounted.
Moreover we cannot but call the count function just because the activity has not been selected. The number of CPU for example must be calculated (counted) even if CPU activity has not been selected because it is needed for different purposes by sar/sadc (creating a new saDD datafile, etc.)

**Comment by odubaj** [comment]
Sorry for that, posting bug description from bugzilla:

Avoid triggering count functions is not collecting data

Description of problem:

The filesystem statistics patches have a regression side-effect of triggering a mount of all automount filesystem and statistic gather even when not selected.

Version-Release number of selected component (if applicable):

sysstat-10.1.5-17.el7

How reproducible:

Always.


Steps to Reproduce:
1. rm -rf sa.new ; strace -fttT -o sadc.trc /usr/lib64/sa/sadc -F -L 1 2 sa.new ; grep mtab sadc.trc


Actual results:

17234 13:38:38.058270 open("/etc/mtab", O_RDONLY) = 3 <0.000428>

and multiple statfs (and stat) calls.

Expected results:

No check of mtab or triggering of automounts.


Additional info:

The problem is triggered due to automatic calling of the f_count & f_count2 dispatch functions in sa_sys_init() in sadc.c regardless of whether the activity is marked for collection.

Whilst the routine adjust the options to not collect if these functions result in no items to collect it does not take into account activities that are already marked not to be collected.

**Pull request merged**
